image: dlp

stages:
- cours
- tme



TME8:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP4 -name ILP4
    com.paracamplus.ilp4.ilp4tme8.test.InterpreterTest
    com.paracamplus.ilp4.ilp4tme8.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml
TME9:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP4 -name ILP4
    com.paracamplus.ilp4.ilp4tme9.test.CompilerTest
  artifacts:
    reports:
      junit: report.xml
